version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ${NACOS_VOLUME}/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: mysql-for-nacos
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    env_file:
      - ../env/mysql.env
    volumes:
      - ${NACOS_VOLUME}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always


